# Generated by Django 5.0.4 on 2024-04-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_user', models.CharField(max_length=10, verbose_name='Категория полльзователя')),
            ],
            options={
                'verbose_name': 'Категория пользователей',
                'verbose_name_plural': 'Категории пользователей',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_work', models.CharField(max_length=20, verbose_name='Место работы')),
                ('position', models.CharField(max_length=20, verbose_name='Должность')),
                ('time_start', models.DateField(verbose_name='Работал с')),
                ('time_end', models.DateField(verbose_name='Работал по')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FilePathField(verbose_name='Фото профиля')),
                ('cat_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.catuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
