# Generated by Django 5.0.4 on 2024-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='def_avatar.jpg', upload_to='avatars', verbose_name='Фото профиля'),
        ),
    ]
