# Generated by Django 5.0.4 on 2024-04-22 10:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_catuser_cat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='def_avatar.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars', verbose_name='Фото профиля'),
        ),
    ]
